# Consolidated docker-compose file with environment variable configuration
services:
  app:
    build: backend
    restart: no
    container_name: snackbar-app-container
    ports:
      - "8080:8080"
      - "5005:5005"  # Debug port
    volumes:
      - .:/app
      - ${MOUNT_AWS_CREDENTIALS}:/root/.aws:ro
    depends_on:
      - mongodb
    environment:
      # Database configuration
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - APP_DB=${APP_DB}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_OPTIONS=${MONGODB_OPTIONS}
      - MONGODB_URI=${MONGODB_URI}
      
      # JWT configuration
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES=${JWT_EXPIRES}
      
      # AWS configuration
      - AWS_REGION=${AWS_REGION}
      - AWS_SQS_PRODUCT_EVENTS_QUEUE_URL=${AWS_SQS_PRODUCT_EVENTS_QUEUE_URL}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_SQS_POLLING_ENABLED=${AWS_SQS_POLLING_ENABLED}
      - AWS_SQS_POLLING_DELAY_MS=${AWS_SQS_POLLING_DELAY_MS}
      - AWS_SQS_MAX_MESSAGES=${AWS_SQS_MAX_MESSAGES}
      
      # Logging configuration
      - LOG_LEVEL_ROOT=${LOG_LEVEL_ROOT}
      - LOG_LEVEL_APP=${LOG_LEVEL_APP}
      - LOG_LEVEL_WEB=${LOG_LEVEL_WEB}
      - LOG_LEVEL_MONGODB=${LOG_LEVEL_MONGODB}

  mongodb:
    image: mongo:8.0.1
    restart: no
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - DB_PORT=${DB_PORT}
    volumes:
      - mongodb_data:/data/db
      - ./database/init-scripts/:/docker-entrypoint-initdb.d/

networks:
  default:
    name: snackbar-network

volumes:
  mongodb_data:
